### ISSUE TITLE
resize not working on firefix - consider css library 

### ISSUE THREAD

**Issue by joshmorel** [chingu-coders/Voyage2-Bears-04#38]
Resizing isn't working on FireFox (see white space below)... Can't say why exactly but at a higher level, I feel we'll run into all sorts of trouble trying to handle this in React with custom stuff. I think we'd be better off adopting a responsive CSS library. This aligns with issue #29 but is also a bug in it's own right.

![resize](https://user-images.githubusercontent.com/10546720/32782029-0d36c16a-c915-11e7-8dfe-0da819f393b1.png)

**Comment by ReeceLangerock** [comment]
I think the biggest hurdle for sitewide responsiveness is going to be for the table displaying resources shown here. As discussed in slack, implementing tiles/cards for small screens could be a solution for this or letting the table overflow and scroll.

**Comment by joshmorel** [comment]
Resolved by #42
