### ISSUE TITLE
add user and authorization

### ISSUE THREAD

**Issue by joshmorel** [chingu-coders/Voyage2-Bears-04#8]
We should add user model/routes and authorization.

@ReeceLangerock do you want to use JWT or cookie for local strategy? I'd lean towards JWT as it's stateless and seems to be the best practice approach. 

Later we can add maybe GitHub or some other OAuth2 strategy.

**Comment by ReeceLangerock** [comment]
I think JWT is probably the best, I researched it a while back but never implemented it. Do we want to use a local strategy or solely rely on Github or another OAuth? I'm ok with either, but using local would add another layer of difficulty in securing user info.

**Comment by joshmorel** [comment]
I'm thinking let's use OAuth alone. There's no need to use local now or really ever (if this takes off, the users will be coders so they'll be GitHub users as well). [cookie-session](https://github.com/expressjs/cookie-session) seems like a nice easy to use, lightweight (no server-side storage) library which I'll use. 

If we were using local strategy, JWT seems better than sessions (still in progress on figuring out exactly why :smile: ).

**Comment by ReeceLangerock** [comment]
Works for me. I agree 95% of users will already have a Github already. If necessary could add google or something but I don't think it will be. 

I used [connect-mongo](https://github.com/jdesboeufs/connect-mongo) for my last project with authentication and it worked pretty nicely, but cookie-session looks like it will be good as well.

**Comment by joshmorel** [comment]
I decided to use jwt instead of sessions. The primary reason is, we can re-use what we create for something like a bots calling the API more easily. We can leave how to store tokens to the client (localStorage with redux in our case to store the token). The secondary reason - it's way easier to mock authentication for testing all the routes. PR into development coming soon.

**Comment by joshmorel** [comment]
Closed by #12
